version: '3'
services:
  database:
    image: mariadb:latest
    restart: always
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
      - dbdata:/var/lib/mysql
    env_file:
      - db.env
    ports:
      - '9487:3306'
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      ADMINER_DEFAULT_SERVER: database
volumes:
  dbdata:
