version: '3'
services:
  app:
    build:
      context: .
      dockerfile: dev.dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./src:/app/src
      - ./test:/app/tests
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.build.json:/app/tsconfig.build.json
      - ./nest-cli.json:/app/nest-cli.json
      - ./.eslintrc.js:/app/.eslintrc.js
      - ./.prettierrc:/app/.prettierrc
    env_file:
      - app.env
    depends_on:
      - database
    ports:
      - '3000:3000'
  database:
    image: mariadb:latest
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
      - db.env
    ports:
      - '3306:3306'
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      ADMINER_DEFAULT_SERVER: database
volumes:
  dbdata:
