name: CD

on:
  release:
    types: [released]

jobs:
  test:
    uses: ./.github/workflows/test.yml
  docker:
    needs: test
    runs-on: ubuntu-latest
    name: "Build Docker image and push to Docker Hub"
    steps:
    - name: Get version string
      id: get-version
      run: |
        tag=${{github.event.release.tag_name}}
        echo "::set-output name=version::${tag:1}"
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ppodds/ncuplus-backend:latest,ppodds/ncuplus-backend:${{ steps.get-version.outputs.version }}
